name: Build
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV

  push:
    paths-ignore:
      - 'docs/**'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set the environment
        run: |
          conda update conda
          $CONDA/bin/conda env create -f scripts/mapd-deps-conda-dev-env.yml --force

      - name: Check stlye
        run: |
          $CONDA/bin/conda run -n omnisci-dev bash -c "find . -name ThirdParty -prune -or \( -name '*.cpp' -print -or -name '*.h' -print \) | xargs clang-format --dry-run --Werror -style=file"

  build:
    uses: ./.github/workflows/build.yml
    with:
      cuda_compiler_version: None

  build-cuda:
    uses: ./.github/workflows/build.yml
    with:
      cuda_compiler_version: 11

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      is_conda_updated: ${{ needs.build.outputs.is_conda_updated }}

  perf:
    needs: build
    uses: ./.github/workflows/perf.yml
    with:
      is_conda_updated: ${{ needs.build.outputs.is_conda_updated }}


