name: Reusable perf test action
on:
  workflow_call: 
    inputs:
      cuda_compiler_version:
        type: string
        default: 'None'
      is_conda_updated:
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      cuda_compiler_version: ${{ inputs.cuda_compiler_version }}
      CONDA_ENV: omnisci-dev

    steps:
      - uses: actions/checkout@v3
        with:
          repository: intel-ai/datasets
          ref: trips-reduced
          path: data

      - name: Set env context
        run: |
          echo CONDA_PATH=$CONDA >>$GITHUB_ENV
          echo RUN_STAMP=${{ runner.os }}-${{ (env.cuda_compiler_version != 'None') && format('cuda{0}', env.cuda_compiler_version) || 'CPU' }} >>$GITHUB_ENV
          echo CONDA_ENV_PATH=$CONDA/envs/${{ env.CONDA_ENV }} >>$GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-build

      - name: Unpack build files
        run: |
          tar -zxf build.tgz

      - name: Download new Conda
        if: ${{ inputs.is_conda_updated == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-conda

      - name: Download old Conda
        if: ${{ inputs.is_conda_updated != 'true' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          name: ${{ env.RUN_STAMP }}-conda
          search_artifacts: true

      - name: Unpack Conda
        run: |
          mkdir -p ${{ env.CONDA_ENV_PATH }}
          tar -zxf conda.tgz -C ${{ env.CONDA_ENV_PATH }}

      - name: Download perf results
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          branch: ${{ github.ref_name }}
          workflow_conclusion: success
          name: ${{ env.RUN_STAMP }}-taxi
          search_artifacts: true
        continue-on-error: true

      - name: Run tests and process results
        run: |
          rm -rf data/.git
          
          $CONDA/bin/conda run -n omnisci-dev pip install matplotlib
          $CONDA/bin/conda run -n omnisci-dev python3 .github/workflows/scripts/run-perf.py 3x build/bin/taxi_reduced --data data

      - name: Upload perf results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.RUN_STAMP }}-taxi
          path: |
            *.pdf
            perf.json

